//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValoresTicket
    {
        public string Clave { get; set; }
        public string Valor { get; set; }
        public long IdTicket { get; set; }
        public long Id { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
